name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: foundry-rs/foundry-toolchain@v1

      - name: Forge version
        run: |
          forge --version

      - name: Forge format
        run: |
          forge fmt --check
        id: fmt

      - name: Forge build
        run: |
          forge build --sizes
        id: build

      - name: Forge test
        run: |
          forge test -vvv
        id: test
