name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry Tests
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
        id: cargo

      - uses: actions/cache@v4
        id: cache
        with:
          key: ${{ runner.os }}-cargo-${{ steps.cargo.outputs.cachekey }}
          restore-keys: |
            ${{ runner.os }}-cargo-
            ${{ runner.os }}-
          path: |
            ~/.cargo

      - name: Install etk assembler
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cargo install --profile release --features cli --locked etk-asm

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: foundry-rs/foundry-toolchain@v1

      - name: Forge version
        run: |
          forge --version

      - name: Forge format
        run: |
          forge fmt --check
        id: fmt

      - name: Forge build
        run: |
          forge build --sizes
        id: build

      - name: Forge coverage
        run: |
          echo '```log' >> $GITHUB_STEP_SUMMARY
          forge coverage --summary --detailed >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        id: coverage

      - name: Forge test
        if: ${{ failure() }}
        run: |
          forge test -vvv
        id: test
